set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN B11 [get_ports hSync]
set_property PACKAGE_PIN B12 [get_ports vSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]

set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]


set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[0]}]

set_property PACKAGE_PIN V11 [get_ports {LEDout[0]}]
set_property PACKAGE_PIN V12 [get_ports {LEDout[1]}]
set_property PACKAGE_PIN V14 [get_ports {LEDout[2]}]
set_property PACKAGE_PIN V15 [get_ports {LEDout[3]}]
set_property PACKAGE_PIN T16 [get_ports {LEDout[4]}]
set_property PACKAGE_PIN U14 [get_ports {LEDout[5]}]
set_property PACKAGE_PIN T15 [get_ports {LEDout[6]}]
set_property PACKAGE_PIN V16 [get_ports {LEDout[7]}]
set_property PACKAGE_PIN U16 [get_ports {LEDout[8]}]
set_property PACKAGE_PIN U17 [get_ports {LEDout[9]}]
set_property PACKAGE_PIN V17 [get_ports {LEDout[10]}]
set_property PACKAGE_PIN R18 [get_ports {LEDout[11]}]
set_property PACKAGE_PIN N14 [get_ports {LEDout[12]}]
set_property PACKAGE_PIN J13 [get_ports {LEDout[13]}]
set_property PACKAGE_PIN K15 [get_ports {LEDout[14]}]
set_property PACKAGE_PIN H17 [get_ports {LEDout[15]}]
